# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='streetaddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
    ]
