# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0002_auto_20180214_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='name',
            new_name='cryptoname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='custname',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stockname',
        ),
    ]
