# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0003_auto_20180214_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='custname',
            new_name='customername',
        ),
    ]
