# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0005_auto_20180214_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='purchase_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
